//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineMusicStore.PlaylistServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/PlaylistService")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PlaylistServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        OnlineMusicStore.PlaylistServiceReference1.CompositeType GetDataUsingDataContract(OnlineMusicStore.PlaylistServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<OnlineMusicStore.PlaylistServiceReference1.CompositeType> GetDataUsingDataContractAsync(OnlineMusicStore.PlaylistServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreatePlaylist", ReplyAction="http://tempuri.org/IService1/CreatePlaylistResponse")]
        bool CreatePlaylist(int userid, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreatePlaylist", ReplyAction="http://tempuri.org/IService1/CreatePlaylistResponse")]
        System.Threading.Tasks.Task<bool> CreatePlaylistAsync(int userid, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddToPlaylist", ReplyAction="http://tempuri.org/IService1/AddToPlaylistResponse")]
        bool AddToPlaylist(int playlistid, int songid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddToPlaylist", ReplyAction="http://tempuri.org/IService1/AddToPlaylistResponse")]
        System.Threading.Tasks.Task<bool> AddToPlaylistAsync(int playlistid, int songid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddToPlaylistWithName", ReplyAction="http://tempuri.org/IService1/AddToPlaylistWithNameResponse")]
        bool AddToPlaylistWithName(string playlistname, int songid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddToPlaylistWithName", ReplyAction="http://tempuri.org/IService1/AddToPlaylistWithNameResponse")]
        System.Threading.Tasks.Task<bool> AddToPlaylistWithNameAsync(string playlistname, int songid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeletePlaylist", ReplyAction="http://tempuri.org/IService1/DeletePlaylistResponse")]
        bool DeletePlaylist(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeletePlaylist", ReplyAction="http://tempuri.org/IService1/DeletePlaylistResponse")]
        System.Threading.Tasks.Task<bool> DeletePlaylistAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : OnlineMusicStore.PlaylistServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<OnlineMusicStore.PlaylistServiceReference1.IService1>, OnlineMusicStore.PlaylistServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public OnlineMusicStore.PlaylistServiceReference1.CompositeType GetDataUsingDataContract(OnlineMusicStore.PlaylistServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<OnlineMusicStore.PlaylistServiceReference1.CompositeType> GetDataUsingDataContractAsync(OnlineMusicStore.PlaylistServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public bool CreatePlaylist(int userid, string name) {
            return base.Channel.CreatePlaylist(userid, name);
        }
        
        public System.Threading.Tasks.Task<bool> CreatePlaylistAsync(int userid, string name) {
            return base.Channel.CreatePlaylistAsync(userid, name);
        }
        
        public bool AddToPlaylist(int playlistid, int songid) {
            return base.Channel.AddToPlaylist(playlistid, songid);
        }
        
        public System.Threading.Tasks.Task<bool> AddToPlaylistAsync(int playlistid, int songid) {
            return base.Channel.AddToPlaylistAsync(playlistid, songid);
        }
        
        public bool AddToPlaylistWithName(string playlistname, int songid) {
            return base.Channel.AddToPlaylistWithName(playlistname, songid);
        }
        
        public System.Threading.Tasks.Task<bool> AddToPlaylistWithNameAsync(string playlistname, int songid) {
            return base.Channel.AddToPlaylistWithNameAsync(playlistname, songid);
        }
        
        public bool DeletePlaylist(int id) {
            return base.Channel.DeletePlaylist(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeletePlaylistAsync(int id) {
            return base.Channel.DeletePlaylistAsync(id);
        }
    }
}
